### PR TITLE
Remove error thrown when running slate build

### LINKED ISSUE #45: Slate build errors when no config.yml file
Technically you shouldn't need a `config.yml` to do a local task like build. If you do you get this ugly output even though the task works as expected.

```
Message:
    `config.yml` does not exist. You need to add a config file before you can upload your theme to Shopify.
Stack:
Error: `config.yml` does not exist. You need to add a config file before you can upload your theme to Shopify.
    at processConfig (/Users/carsonshold/Documents/Projects/slate/node_modules/@shopify/slate-tools/lib/tasks/build-config.js:18:11)
    at Gulp.gulp.task (/Users/carsonshold/Documents/Projects/slate/node_modules/@shopify/slate-tools/lib/tasks/build-config.js:37:10)
    at module.exports (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:214:10)
    at /Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:279:18
    at finish (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:214:10)
    at /Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:279:18
    at finish (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:134:8)
```

### Why should this be fixed?

I'm writing up some Slate usage docs that suggest running `slate build` before the steps of creating an app and config file. Quicker to see it work = more trust in the tool (or so is my thinking).

If we can remove that error from `build` we're golden. 

cc @Shopify/themes-fed 
@macdonaldr93 @m-ux

### PR DESCRIPTION
**Pull request by chrisberthe**
Fixes #45 and fixes Shopify/slate-cli#118.

Not sure if this is the best approach but wanted your thoughts. This removes the `throw new Error()` output when there isn't a `config.yml` in the theme root folder and when `slate build` is ran.

I brought the error logic to the `invalidate:id` task, which is called for `slate watch` and `slate deploy`. This ensures the config has been created, otherwise the process will exit before it "links" the local theme folder to the store.

Output when running either sync command:

image

The `slate build` command will build without any errors now.

@cshold

### CODE REVIEW

File: src/tasks/deploy-utils.js [hunk 1]
```diff
@@ -68,7 +68,17 @@ function validateId(settings) {
  */
 
 gulp.task('validate:id', () => {
-  const file = fs.readFileSync(config.tkConfig, 'utf8');
+  let file;
```
Comment (t-kelly) [inline src/tasks/deploy-utils.js]: Are we cool with a 40 line function? Could this be cleaned up while touching this code?

File: src/tasks/build-config.js [hunk 2]
```diff
@@ -11,11 +10,6 @@ const messages = require('./includes/messages.js');
 function processConfig(file) {
   messages.logProcessFiles('build:config');
 
-  // eslint-disable-next-line no-sync, node/no-deprecated-api
-  if (!fs.existsSync(file)) {
```
Comment (t-kelly) [inline src/tasks/build-config.js]: Nice to see this living in `deploy` instead of `build`. Makes sense.

File: src/tasks/deploy-utils.js (hunk 1 above)
Comment (chrisberthe) [inline src/tasks/deploy-utils.js]: Could probably be part of a future clean-up PR. Anything obvious stand out for you here?

File: src/tasks/deploy-utils.js [hunk 3]
```diff
@@ -66,9 +66,18 @@ function validateId(settings) {
...
  * @private
  */
-
 gulp.task('validate:id', () => {
-  const file = fs.readFileSync(config.tkConfig, 'utf8');
+  let file;
+
+  try {
+    file = fs.readFileSync(config.tkConfig, 'utf8');
+  } catch (err) {
```
Comment (macdonaldr93) [inline src/tasks/deploy-utils.js]: You might want to handle this err a little bit. You could just have a permission error on your config file and then we're telling the user that it doesn't exist.

I think it would make sense to say if err is `ENOENT` then do this,
 otherwise, actually throw the error so that the user could debug the problem.
 (https://nodejs.org/api/errors.html#errors_common_system_errors)

Comment (macdonaldr93) [inline src/tasks/deploy-utils.js]: Update why don't you use `existsSync`? Only `exists` was deprecated. (https://nodejs.org/api/fs.html#fs_fs_existssync_path)

**Comment by NathanPJF** [comment]
🎩
😍  

Works great!
